#include <Servo.h>

Servo windowControl;

void setup(){
  windowControl.attach(8);
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop(){
  int rotation = 0;
  windowControl.write(rotation);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation += 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);

  // Returning back to 0
  windowControl.write(rotation);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  windowControl.write(rotation -= 10);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
}